/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.pacbio.common.models.pipelines.viewrules;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PipelineOptionView extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PipelineOptionView\",\"namespace\":\"com.pacbio.common.models.pipelines.viewrules\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"Tool Contract option id (e.g., pbcommand.task_options.my_option)\"},{\"name\":\"hidden\",\"type\":\"boolean\",\"doc\":\"Should option be hidden\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Tool Contract option id (e.g., pbcommand.task_options.my_option) */
  @Deprecated public java.lang.CharSequence id;
  /** Should option be hidden */
  @Deprecated public boolean hidden;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public PipelineOptionView() {}

  /**
   * All-args constructor.
   */
  public PipelineOptionView(java.lang.CharSequence id, java.lang.Boolean hidden) {
    this.id = id;
    this.hidden = hidden;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return hidden;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: hidden = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * Tool Contract option id (e.g., pbcommand.task_options.my_option)   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * Tool Contract option id (e.g., pbcommand.task_options.my_option)   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'hidden' field.
   * Should option be hidden   */
  public java.lang.Boolean getHidden() {
    return hidden;
  }

  /**
   * Sets the value of the 'hidden' field.
   * Should option be hidden   * @param value the value to set.
   */
  public void setHidden(java.lang.Boolean value) {
    this.hidden = value;
  }

  /** Creates a new PipelineOptionView RecordBuilder */
  public static com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder newBuilder() {
    return new com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder();
  }
  
  /** Creates a new PipelineOptionView RecordBuilder by copying an existing Builder */
  public static com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder newBuilder(com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder other) {
    return new com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder(other);
  }
  
  /** Creates a new PipelineOptionView RecordBuilder by copying an existing PipelineOptionView instance */
  public static com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder newBuilder(com.pacbio.common.models.pipelines.viewrules.PipelineOptionView other) {
    return new com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder(other);
  }
  
  /**
   * RecordBuilder for PipelineOptionView instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PipelineOptionView>
    implements org.apache.avro.data.RecordBuilder<PipelineOptionView> {

    private java.lang.CharSequence id;
    private boolean hidden;

    /** Creates a new Builder */
    private Builder() {
      super(com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hidden)) {
        this.hidden = data().deepCopy(fields()[1].schema(), other.hidden);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PipelineOptionView instance */
    private Builder(com.pacbio.common.models.pipelines.viewrules.PipelineOptionView other) {
            super(com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hidden)) {
        this.hidden = data().deepCopy(fields()[1].schema(), other.hidden);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'hidden' field */
    public java.lang.Boolean getHidden() {
      return hidden;
    }
    
    /** Sets the value of the 'hidden' field */
    public com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder setHidden(boolean value) {
      validate(fields()[1], value);
      this.hidden = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'hidden' field has been set */
    public boolean hasHidden() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'hidden' field */
    public com.pacbio.common.models.pipelines.viewrules.PipelineOptionView.Builder clearHidden() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public PipelineOptionView build() {
      try {
        PipelineOptionView record = new PipelineOptionView();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.hidden = fieldSetFlags()[1] ? this.hidden : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
