/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package org.wso2.carbon.apimgt.rest.api.publisher.models

import org.joda.time.DateTime


case class Subscription (
  subscriptionId: Option[String],
  applicationId: String,
  apiIdentifier: String,
  tier: String,
  status: Option[SubscriptionEnums.Status])

object SubscriptionEnums {

  type Status = Status.Value
  
  object Status extends Enumeration {
    val BLOCKED = Value("BLOCKED")
    val PRODONLYBLOCKED = Value("PROD_ONLY_BLOCKED")
    val UNBLOCKED = Value("UNBLOCKED")
    val ONHOLD = Value("ON_HOLD")
    val REJECTED = Value("REJECTED")
  }

  
}

