//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.17 at 02:46:42 PM PDT 
//


package com.pacificbiosciences.pacbiopipelinestats;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.pacificbiosciences.pacbiobasedatamodel.StatsContinuousDistType;
import com.pacificbiosciences.pacbiobasedatamodel.StatsDiscreteDistType;
import com.pacificbiosciences.pacbiobasedatamodel.StatsTimeSeriesType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pacificbiosciences.pacbiopipelinestats package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SnrRatioEdgeToCntr2_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SnrRatioEdgeToCntr_2");
    private final static QName _HqRegionSnrDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "HqRegionSnrDist");
    private final static QName _SnrRatioEdgeToCntr0_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SnrRatioEdgeToCntr_0");
    private final static QName _BinCount_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BinCount");
    private final static QName _MaxSlopePauseFractionVsT_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MaxSlopePauseFractionVsT");
    private final static QName _BaselineLevelSequencingDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaselineLevelSequencingDist");
    private final static QName _NumSequencingZmws_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "NumSequencingZmws");
    private final static QName _Sample95ThPct_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "Sample95thPct");
    private final static QName _PausinessDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "PausinessDist");
    private final static QName _TMaxSlopePauseFraction_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TMaxSlopePauseFraction");
    private final static QName _SampleMed_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SampleMed");
    private final static QName _InsertReadQualDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "InsertReadQualDist");
    private final static QName _MaxBaseRateRatioVsT_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MaxBaseRateRatioVsT");
    private final static QName _YieldCvOverRegions_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "YieldCvOverRegions");
    private final static QName _BaselineLevelDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaselineLevelDist");
    private final static QName _SnrDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SnrDist");
    private final static QName _MaxPauseFractionVsT_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MaxPauseFractionVsT");
    private final static QName _NumFramesDropped_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "NumFramesDropped");
    private final static QName _HqBaseFractionDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "HqBaseFractionDist");
    private final static QName _RmBasQvDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "RmBasQvDist");
    private final static QName _NumFailedDmeZmws_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "NumFailedDmeZmws");
    private final static QName _SgnMaxSlopeBaseRateRatio_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SgnMaxSlopeBaseRateRatio");
    private final static QName _ShortInsertFraction_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "ShortInsertFraction");
    private final static QName _ProdDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "ProdDist");
    private final static QName _InsertReadLenDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "InsertReadLenDist");
    private final static QName _TMaxPauseFraction_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TMaxPauseFraction");
    private final static QName _SampleStd_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SampleStd");
    private final static QName _BinWidth_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BinWidth");
    private final static QName _TraceHighClippedFractionDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TraceHighClippedFractionDist");
    private final static QName _NumBins_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "NumBins");
    private final static QName _MaxSlopeBaseRateRatioVsT_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MaxSlopeBaseRateRatioVsT");
    private final static QName _PulseWidthDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "PulseWidthDist");
    private final static QName _LocalYieldDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "LocalYieldDist");
    private final static QName _SpectralDiagRRDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SpectralDiagRRDist");
    private final static QName _ControlReadLenDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "ControlReadLenDist");
    private final static QName _PkMidCVDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "PkMidCVDist");
    private final static QName _AdapterDimerFraction_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "AdapterDimerFraction");
    private final static QName _YieldChngCntrToEdge_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "YieldChngCntrToEdge");
    private final static QName _MinOutlierValue_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MinOutlierValue");
    private final static QName _MedianInsertDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MedianInsertDist");
    private final static QName _BaselineLevelAntiholeDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaselineLevelAntiholeDist");
    private final static QName _LocalSnrDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "LocalSnrDist");
    private final static QName _PauseFractionVsT_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "PauseFractionVsT");
    private final static QName _IsReadsFraction_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "IsReadsFraction");
    private final static QName _BaseIpdDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaseIpdDist");
    private final static QName _TMaxSlopeBaseRateRatio_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TMaxSlopeBaseRateRatio");
    private final static QName _ControlReadQualDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "ControlReadQualDist");
    private final static QName _TotalBaseFractionPerChannel_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TotalBaseFractionPerChannel");
    private final static QName _SampleMean_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SampleMean");
    private final static QName _NumFailedSnrFilterZmws_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "NumFailedSnrFilterZmws");
    private final static QName _ReadTypeDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "ReadTypeDist");
    private final static QName _FailedZmwClippedHighFraction_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "FailedZmwClippedHighFraction");
    private final static QName _TotalBaseFractionValue_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TotalBaseFractionValue");
    private final static QName _MetricDescription_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MetricDescription");
    private final static QName _MaxOutlierValue_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MaxOutlierValue");
    private final static QName _PkMidCVValue_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "PkMidCVValue");
    private final static QName _FailedZmwClippedLowFraction_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "FailedZmwClippedLowFraction");
    private final static QName _BaseFileSize_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaseFileSize");
    private final static QName _BaselineStdDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaselineStdDist");
    private final static QName _ReadLenDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "ReadLenDist");
    private final static QName _MovieLength_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MovieLength");
    private final static QName _BaseRateDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaseRateDist");
    private final static QName _BinLabel_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BinLabel");
    private final static QName _MaxBinValue_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MaxBinValue");
    private final static QName _TraceFileSize_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TraceFileSize");
    private final static QName _LocalBaseRateDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "LocalBaseRateDist");
    private final static QName _BaselineLevelAntimirrorDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaselineLevelAntimirrorDist");
    private final static QName _TMaxBaseRateRatio_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TMaxBaseRateRatio");
    private final static QName _BaseRateChngStrtToEnd_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaseRateChngStrtToEnd");
    private final static QName _SampleSize_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "SampleSize");
    private final static QName _BaselineLevelFiducialDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaselineLevelFiducialDist");
    private final static QName _BaseWidthDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaseWidthDist");
    private final static QName _PulseRateDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "PulseRateDist");
    private final static QName _PkMidCVPerChannel_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "PkMidCVPerChannel");
    private final static QName _PulseFileSize_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "PulseFileSize");
    private final static QName _ReadQualDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "ReadQualDist");
    private final static QName _TraceLowClippedFractionDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TraceLowClippedFractionDist");
    private final static QName _TraceClippedFractionDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "TraceClippedFractionDist");
    private final static QName _MinBinValue_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MinBinValue");
    private final static QName _MovieReadQualDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MovieReadQualDist");
    private final static QName _HqBasPkMidDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "HqBasPkMidDist");
    private final static QName _NumUnfilteredBasecallsDist_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "NumUnfilteredBasecallsDist");
    private final static QName _MovieName_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "MovieName");
    private final static QName _BaseRateRatioVsT_QNAME = new QName("http://pacificbiosciences.com/PacBioPipelineStats.xsd", "BaseRateRatioVsT");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pacificbiosciences.pacbiopipelinestats
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PkMidCV }
     * 
     */
    public PkMidCV createPkMidCV() {
        return new PkMidCV();
    }

    /**
     * Create an instance of {@link PipeStats }
     * 
     */
    public PipeStats createPipeStats() {
        return new PipeStats();
    }

    /**
     * Create an instance of {@link TotalBaseFraction }
     * 
     */
    public TotalBaseFraction createTotalBaseFraction() {
        return new TotalBaseFraction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SnrRatioEdgeToCntr_2")
    public JAXBElement<Double> createSnrRatioEdgeToCntr2(Double value) {
        return new JAXBElement<Double>(_SnrRatioEdgeToCntr2_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "HqRegionSnrDist")
    public JAXBElement<StatsContinuousDistType> createHqRegionSnrDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_HqRegionSnrDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SnrRatioEdgeToCntr_0")
    public JAXBElement<Double> createSnrRatioEdgeToCntr0(Double value) {
        return new JAXBElement<Double>(_SnrRatioEdgeToCntr0_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BinCount")
    public JAXBElement<Integer> createBinCount(Integer value) {
        return new JAXBElement<Integer>(_BinCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MaxSlopePauseFractionVsT")
    public JAXBElement<Double> createMaxSlopePauseFractionVsT(Double value) {
        return new JAXBElement<Double>(_MaxSlopePauseFractionVsT_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaselineLevelSequencingDist")
    public JAXBElement<StatsContinuousDistType> createBaselineLevelSequencingDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaselineLevelSequencingDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "NumSequencingZmws")
    public JAXBElement<Double> createNumSequencingZmws(Double value) {
        return new JAXBElement<Double>(_NumSequencingZmws_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "Sample95thPct")
    public JAXBElement<Double> createSample95ThPct(Double value) {
        return new JAXBElement<Double>(_Sample95ThPct_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "PausinessDist")
    public JAXBElement<StatsContinuousDistType> createPausinessDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_PausinessDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TMaxSlopePauseFraction")
    public JAXBElement<Integer> createTMaxSlopePauseFraction(Integer value) {
        return new JAXBElement<Integer>(_TMaxSlopePauseFraction_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SampleMed")
    public JAXBElement<Double> createSampleMed(Double value) {
        return new JAXBElement<Double>(_SampleMed_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "InsertReadQualDist")
    public JAXBElement<StatsContinuousDistType> createInsertReadQualDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_InsertReadQualDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MaxBaseRateRatioVsT")
    public JAXBElement<Double> createMaxBaseRateRatioVsT(Double value) {
        return new JAXBElement<Double>(_MaxBaseRateRatioVsT_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "YieldCvOverRegions")
    public JAXBElement<Double> createYieldCvOverRegions(Double value) {
        return new JAXBElement<Double>(_YieldCvOverRegions_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaselineLevelDist")
    public JAXBElement<StatsContinuousDistType> createBaselineLevelDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaselineLevelDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SnrDist")
    public JAXBElement<StatsContinuousDistType> createSnrDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_SnrDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MaxPauseFractionVsT")
    public JAXBElement<Double> createMaxPauseFractionVsT(Double value) {
        return new JAXBElement<Double>(_MaxPauseFractionVsT_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "NumFramesDropped")
    public JAXBElement<Double> createNumFramesDropped(Double value) {
        return new JAXBElement<Double>(_NumFramesDropped_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "HqBaseFractionDist")
    public JAXBElement<StatsContinuousDistType> createHqBaseFractionDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_HqBaseFractionDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "RmBasQvDist")
    public JAXBElement<StatsContinuousDistType> createRmBasQvDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_RmBasQvDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "NumFailedDmeZmws")
    public JAXBElement<Integer> createNumFailedDmeZmws(Integer value) {
        return new JAXBElement<Integer>(_NumFailedDmeZmws_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SgnMaxSlopeBaseRateRatio")
    public JAXBElement<Integer> createSgnMaxSlopeBaseRateRatio(Integer value) {
        return new JAXBElement<Integer>(_SgnMaxSlopeBaseRateRatio_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "ShortInsertFraction")
    public JAXBElement<Double> createShortInsertFraction(Double value) {
        return new JAXBElement<Double>(_ShortInsertFraction_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsDiscreteDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "ProdDist")
    public JAXBElement<StatsDiscreteDistType> createProdDist(StatsDiscreteDistType value) {
        return new JAXBElement<StatsDiscreteDistType>(_ProdDist_QNAME, StatsDiscreteDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "InsertReadLenDist")
    public JAXBElement<StatsContinuousDistType> createInsertReadLenDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_InsertReadLenDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TMaxPauseFraction")
    public JAXBElement<Integer> createTMaxPauseFraction(Integer value) {
        return new JAXBElement<Integer>(_TMaxPauseFraction_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SampleStd")
    public JAXBElement<Double> createSampleStd(Double value) {
        return new JAXBElement<Double>(_SampleStd_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BinWidth")
    public JAXBElement<Double> createBinWidth(Double value) {
        return new JAXBElement<Double>(_BinWidth_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TraceHighClippedFractionDist")
    public JAXBElement<StatsContinuousDistType> createTraceHighClippedFractionDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_TraceHighClippedFractionDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "NumBins")
    public JAXBElement<Integer> createNumBins(Integer value) {
        return new JAXBElement<Integer>(_NumBins_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MaxSlopeBaseRateRatioVsT")
    public JAXBElement<Double> createMaxSlopeBaseRateRatioVsT(Double value) {
        return new JAXBElement<Double>(_MaxSlopeBaseRateRatioVsT_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "PulseWidthDist")
    public JAXBElement<StatsContinuousDistType> createPulseWidthDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_PulseWidthDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "LocalYieldDist")
    public JAXBElement<StatsContinuousDistType> createLocalYieldDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_LocalYieldDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SpectralDiagRRDist")
    public JAXBElement<StatsContinuousDistType> createSpectralDiagRRDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_SpectralDiagRRDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "ControlReadLenDist")
    public JAXBElement<StatsContinuousDistType> createControlReadLenDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_ControlReadLenDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "PkMidCVDist")
    public JAXBElement<StatsContinuousDistType> createPkMidCVDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_PkMidCVDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "AdapterDimerFraction")
    public JAXBElement<Double> createAdapterDimerFraction(Double value) {
        return new JAXBElement<Double>(_AdapterDimerFraction_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "YieldChngCntrToEdge")
    public JAXBElement<Double> createYieldChngCntrToEdge(Double value) {
        return new JAXBElement<Double>(_YieldChngCntrToEdge_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MinOutlierValue")
    public JAXBElement<Double> createMinOutlierValue(Double value) {
        return new JAXBElement<Double>(_MinOutlierValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MedianInsertDist")
    public JAXBElement<StatsContinuousDistType> createMedianInsertDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_MedianInsertDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaselineLevelAntiholeDist")
    public JAXBElement<StatsContinuousDistType> createBaselineLevelAntiholeDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaselineLevelAntiholeDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "LocalSnrDist")
    public JAXBElement<StatsContinuousDistType> createLocalSnrDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_LocalSnrDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsTimeSeriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "PauseFractionVsT")
    public JAXBElement<StatsTimeSeriesType> createPauseFractionVsT(StatsTimeSeriesType value) {
        return new JAXBElement<StatsTimeSeriesType>(_PauseFractionVsT_QNAME, StatsTimeSeriesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "IsReadsFraction")
    public JAXBElement<Double> createIsReadsFraction(Double value) {
        return new JAXBElement<Double>(_IsReadsFraction_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaseIpdDist")
    public JAXBElement<StatsContinuousDistType> createBaseIpdDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaseIpdDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TMaxSlopeBaseRateRatio")
    public JAXBElement<Integer> createTMaxSlopeBaseRateRatio(Integer value) {
        return new JAXBElement<Integer>(_TMaxSlopeBaseRateRatio_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "ControlReadQualDist")
    public JAXBElement<StatsContinuousDistType> createControlReadQualDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_ControlReadQualDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TotalBaseFraction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TotalBaseFractionPerChannel")
    public JAXBElement<TotalBaseFraction> createTotalBaseFractionPerChannel(TotalBaseFraction value) {
        return new JAXBElement<TotalBaseFraction>(_TotalBaseFractionPerChannel_QNAME, TotalBaseFraction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SampleMean")
    public JAXBElement<Double> createSampleMean(Double value) {
        return new JAXBElement<Double>(_SampleMean_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "NumFailedSnrFilterZmws")
    public JAXBElement<Integer> createNumFailedSnrFilterZmws(Integer value) {
        return new JAXBElement<Integer>(_NumFailedSnrFilterZmws_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsDiscreteDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "ReadTypeDist")
    public JAXBElement<StatsDiscreteDistType> createReadTypeDist(StatsDiscreteDistType value) {
        return new JAXBElement<StatsDiscreteDistType>(_ReadTypeDist_QNAME, StatsDiscreteDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "FailedZmwClippedHighFraction")
    public JAXBElement<Double> createFailedZmwClippedHighFraction(Double value) {
        return new JAXBElement<Double>(_FailedZmwClippedHighFraction_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TotalBaseFractionValue")
    public JAXBElement<Double> createTotalBaseFractionValue(Double value) {
        return new JAXBElement<Double>(_TotalBaseFractionValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MetricDescription")
    public JAXBElement<String> createMetricDescription(String value) {
        return new JAXBElement<String>(_MetricDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MaxOutlierValue")
    public JAXBElement<Double> createMaxOutlierValue(Double value) {
        return new JAXBElement<Double>(_MaxOutlierValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "PkMidCVValue")
    public JAXBElement<Double> createPkMidCVValue(Double value) {
        return new JAXBElement<Double>(_PkMidCVValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "FailedZmwClippedLowFraction")
    public JAXBElement<Double> createFailedZmwClippedLowFraction(Double value) {
        return new JAXBElement<Double>(_FailedZmwClippedLowFraction_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaseFileSize")
    public JAXBElement<Long> createBaseFileSize(Long value) {
        return new JAXBElement<Long>(_BaseFileSize_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaselineStdDist")
    public JAXBElement<StatsContinuousDistType> createBaselineStdDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaselineStdDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "ReadLenDist")
    public JAXBElement<StatsContinuousDistType> createReadLenDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_ReadLenDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MovieLength")
    public JAXBElement<Double> createMovieLength(Double value) {
        return new JAXBElement<Double>(_MovieLength_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaseRateDist")
    public JAXBElement<StatsContinuousDistType> createBaseRateDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaseRateDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BinLabel")
    public JAXBElement<String> createBinLabel(String value) {
        return new JAXBElement<String>(_BinLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MaxBinValue")
    public JAXBElement<Double> createMaxBinValue(Double value) {
        return new JAXBElement<Double>(_MaxBinValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TraceFileSize")
    public JAXBElement<Long> createTraceFileSize(Long value) {
        return new JAXBElement<Long>(_TraceFileSize_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "LocalBaseRateDist")
    public JAXBElement<StatsContinuousDistType> createLocalBaseRateDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_LocalBaseRateDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaselineLevelAntimirrorDist")
    public JAXBElement<StatsContinuousDistType> createBaselineLevelAntimirrorDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaselineLevelAntimirrorDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TMaxBaseRateRatio")
    public JAXBElement<Integer> createTMaxBaseRateRatio(Integer value) {
        return new JAXBElement<Integer>(_TMaxBaseRateRatio_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaseRateChngStrtToEnd")
    public JAXBElement<Double> createBaseRateChngStrtToEnd(Double value) {
        return new JAXBElement<Double>(_BaseRateChngStrtToEnd_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "SampleSize")
    public JAXBElement<Integer> createSampleSize(Integer value) {
        return new JAXBElement<Integer>(_SampleSize_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaselineLevelFiducialDist")
    public JAXBElement<StatsContinuousDistType> createBaselineLevelFiducialDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaselineLevelFiducialDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaseWidthDist")
    public JAXBElement<StatsContinuousDistType> createBaseWidthDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_BaseWidthDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "PulseRateDist")
    public JAXBElement<StatsContinuousDistType> createPulseRateDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_PulseRateDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PkMidCV }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "PkMidCVPerChannel")
    public JAXBElement<PkMidCV> createPkMidCVPerChannel(PkMidCV value) {
        return new JAXBElement<PkMidCV>(_PkMidCVPerChannel_QNAME, PkMidCV.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "PulseFileSize")
    public JAXBElement<Long> createPulseFileSize(Long value) {
        return new JAXBElement<Long>(_PulseFileSize_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "ReadQualDist")
    public JAXBElement<StatsContinuousDistType> createReadQualDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_ReadQualDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TraceLowClippedFractionDist")
    public JAXBElement<StatsContinuousDistType> createTraceLowClippedFractionDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_TraceLowClippedFractionDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "TraceClippedFractionDist")
    public JAXBElement<StatsContinuousDistType> createTraceClippedFractionDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_TraceClippedFractionDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MinBinValue")
    public JAXBElement<Double> createMinBinValue(Double value) {
        return new JAXBElement<Double>(_MinBinValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MovieReadQualDist")
    public JAXBElement<StatsContinuousDistType> createMovieReadQualDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_MovieReadQualDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "HqBasPkMidDist")
    public JAXBElement<StatsContinuousDistType> createHqBasPkMidDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_HqBasPkMidDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsContinuousDistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "NumUnfilteredBasecallsDist")
    public JAXBElement<StatsContinuousDistType> createNumUnfilteredBasecallsDist(StatsContinuousDistType value) {
        return new JAXBElement<StatsContinuousDistType>(_NumUnfilteredBasecallsDist_QNAME, StatsContinuousDistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "MovieName")
    public JAXBElement<String> createMovieName(String value) {
        return new JAXBElement<String>(_MovieName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatsTimeSeriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioPipelineStats.xsd", name = "BaseRateRatioVsT")
    public JAXBElement<StatsTimeSeriesType> createBaseRateRatioVsT(StatsTimeSeriesType value) {
        return new JAXBElement<StatsTimeSeriesType>(_BaseRateRatioVsT_QNAME, StatsTimeSeriesType.class, null, value);
    }

}
