/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.pacbio.common.models.reports;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PlotGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlotGroup\",\"namespace\":\"com.pacbio.common.models.reports\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"legend\",\"type\":[\"string\",\"null\"],\"desc\":\"Not clear what the usecase is of this\"},{\"name\":\"thumbnail\",\"type\":[\"string\",\"null\"]},{\"name\":\"plots\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ReportPlot\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"desc\":\"Plot Id\"},{\"name\":\"image\",\"type\":\"string\",\"desc\":\"Relative Path to Image\"},{\"name\":\"caption\",\"type\":[\"string\",\"null\"],\"desc\":\"Caption of the Plot\"},{\"name\":\"thumbnail\",\"type\":[\"string\",\"null\"],\"desc\":\"Relative path to thumbnail of the Plot\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence legend;
  @Deprecated public java.lang.CharSequence thumbnail;
  @Deprecated public java.util.List<com.pacbio.common.models.reports.ReportPlot> plots;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public PlotGroup() {}

  /**
   * All-args constructor.
   */
  public PlotGroup(java.lang.CharSequence id, java.lang.CharSequence title, java.lang.CharSequence legend, java.lang.CharSequence thumbnail, java.util.List<com.pacbio.common.models.reports.ReportPlot> plots) {
    this.id = id;
    this.title = title;
    this.legend = legend;
    this.thumbnail = thumbnail;
    this.plots = plots;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return title;
    case 2: return legend;
    case 3: return thumbnail;
    case 4: return plots;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: legend = (java.lang.CharSequence)value$; break;
    case 3: thumbnail = (java.lang.CharSequence)value$; break;
    case 4: plots = (java.util.List<com.pacbio.common.models.reports.ReportPlot>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'legend' field.
   */
  public java.lang.CharSequence getLegend() {
    return legend;
  }

  /**
   * Sets the value of the 'legend' field.
   * @param value the value to set.
   */
  public void setLegend(java.lang.CharSequence value) {
    this.legend = value;
  }

  /**
   * Gets the value of the 'thumbnail' field.
   */
  public java.lang.CharSequence getThumbnail() {
    return thumbnail;
  }

  /**
   * Sets the value of the 'thumbnail' field.
   * @param value the value to set.
   */
  public void setThumbnail(java.lang.CharSequence value) {
    this.thumbnail = value;
  }

  /**
   * Gets the value of the 'plots' field.
   */
  public java.util.List<com.pacbio.common.models.reports.ReportPlot> getPlots() {
    return plots;
  }

  /**
   * Sets the value of the 'plots' field.
   * @param value the value to set.
   */
  public void setPlots(java.util.List<com.pacbio.common.models.reports.ReportPlot> value) {
    this.plots = value;
  }

  /** Creates a new PlotGroup RecordBuilder */
  public static com.pacbio.common.models.reports.PlotGroup.Builder newBuilder() {
    return new com.pacbio.common.models.reports.PlotGroup.Builder();
  }
  
  /** Creates a new PlotGroup RecordBuilder by copying an existing Builder */
  public static com.pacbio.common.models.reports.PlotGroup.Builder newBuilder(com.pacbio.common.models.reports.PlotGroup.Builder other) {
    return new com.pacbio.common.models.reports.PlotGroup.Builder(other);
  }
  
  /** Creates a new PlotGroup RecordBuilder by copying an existing PlotGroup instance */
  public static com.pacbio.common.models.reports.PlotGroup.Builder newBuilder(com.pacbio.common.models.reports.PlotGroup other) {
    return new com.pacbio.common.models.reports.PlotGroup.Builder(other);
  }
  
  /**
   * RecordBuilder for PlotGroup instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlotGroup>
    implements org.apache.avro.data.RecordBuilder<PlotGroup> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence title;
    private java.lang.CharSequence legend;
    private java.lang.CharSequence thumbnail;
    private java.util.List<com.pacbio.common.models.reports.ReportPlot> plots;

    /** Creates a new Builder */
    private Builder() {
      super(com.pacbio.common.models.reports.PlotGroup.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.pacbio.common.models.reports.PlotGroup.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.legend)) {
        this.legend = data().deepCopy(fields()[2].schema(), other.legend);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.thumbnail)) {
        this.thumbnail = data().deepCopy(fields()[3].schema(), other.thumbnail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.plots)) {
        this.plots = data().deepCopy(fields()[4].schema(), other.plots);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PlotGroup instance */
    private Builder(com.pacbio.common.models.reports.PlotGroup other) {
            super(com.pacbio.common.models.reports.PlotGroup.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.legend)) {
        this.legend = data().deepCopy(fields()[2].schema(), other.legend);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.thumbnail)) {
        this.thumbnail = data().deepCopy(fields()[3].schema(), other.thumbnail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.plots)) {
        this.plots = data().deepCopy(fields()[4].schema(), other.plots);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'title' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'legend' field */
    public java.lang.CharSequence getLegend() {
      return legend;
    }
    
    /** Sets the value of the 'legend' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder setLegend(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.legend = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'legend' field has been set */
    public boolean hasLegend() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'legend' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder clearLegend() {
      legend = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'thumbnail' field */
    public java.lang.CharSequence getThumbnail() {
      return thumbnail;
    }
    
    /** Sets the value of the 'thumbnail' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder setThumbnail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.thumbnail = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'thumbnail' field has been set */
    public boolean hasThumbnail() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'thumbnail' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder clearThumbnail() {
      thumbnail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'plots' field */
    public java.util.List<com.pacbio.common.models.reports.ReportPlot> getPlots() {
      return plots;
    }
    
    /** Sets the value of the 'plots' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder setPlots(java.util.List<com.pacbio.common.models.reports.ReportPlot> value) {
      validate(fields()[4], value);
      this.plots = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'plots' field has been set */
    public boolean hasPlots() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'plots' field */
    public com.pacbio.common.models.reports.PlotGroup.Builder clearPlots() {
      plots = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public PlotGroup build() {
      try {
        PlotGroup record = new PlotGroup();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.legend = fieldSetFlags()[2] ? this.legend : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.thumbnail = fieldSetFlags()[3] ? this.thumbnail : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.plots = fieldSetFlags()[4] ? this.plots : (java.util.List<com.pacbio.common.models.reports.ReportPlot>) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
