//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.18 at 03:16:30 PM PDT 
//


package com.pacificbiosciences.pacbiobasedatamodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnalogType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnalogType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}BaseEntityType">
 *       &lt;sequence>
 *         &lt;element name="Spectrum">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Values">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}float" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="NumberFilterBins" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RelativeAmplitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="IntraPulseXsnCV" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="InterPulseXsnCV" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="DiffusionXsnCV" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="PulseWidthMeanSeconds" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="IpdMeanSeconds" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Base" type="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}SupportedNucleotides" />
 *       &lt;attribute name="Nucleotide" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Wavelength" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="CompoundID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LotID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnalogType", propOrder = {
    "spectrum",
    "relativeAmplitude",
    "intraPulseXsnCV",
    "interPulseXsnCV",
    "diffusionXsnCV",
    "pulseWidthMeanSeconds",
    "ipdMeanSeconds"
})
@XmlSeeAlso({
    ConfigSetAnalog.class,
    DyeSetAnalog.class
})
public class AnalogType
    extends BaseEntityType
{

    @XmlElement(name = "Spectrum", required = true)
    protected AnalogType.Spectrum spectrum;
    @XmlElement(name = "RelativeAmplitude")
    protected float relativeAmplitude;
    @XmlElement(name = "IntraPulseXsnCV")
    protected float intraPulseXsnCV;
    @XmlElement(name = "InterPulseXsnCV")
    protected float interPulseXsnCV;
    @XmlElement(name = "DiffusionXsnCV")
    protected float diffusionXsnCV;
    @XmlElement(name = "PulseWidthMeanSeconds")
    protected Float pulseWidthMeanSeconds;
    @XmlElement(name = "IpdMeanSeconds")
    protected Float ipdMeanSeconds;
    @XmlAttribute(name = "Base")
    protected SupportedNucleotides base;
    @XmlAttribute(name = "Nucleotide")
    protected String nucleotide;
    @XmlAttribute(name = "Wavelength")
    protected Float wavelength;
    @XmlAttribute(name = "CompoundID")
    protected String compoundID;
    @XmlAttribute(name = "LotID")
    protected String lotID;

    /**
     * Gets the value of the spectrum property.
     * 
     * @return
     *     possible object is
     *     {@link AnalogType.Spectrum }
     *     
     */
    public AnalogType.Spectrum getSpectrum() {
        return spectrum;
    }

    /**
     * Sets the value of the spectrum property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalogType.Spectrum }
     *     
     */
    public void setSpectrum(AnalogType.Spectrum value) {
        this.spectrum = value;
    }

    /**
     * Gets the value of the relativeAmplitude property.
     * 
     */
    public float getRelativeAmplitude() {
        return relativeAmplitude;
    }

    /**
     * Sets the value of the relativeAmplitude property.
     * 
     */
    public void setRelativeAmplitude(float value) {
        this.relativeAmplitude = value;
    }

    /**
     * Gets the value of the intraPulseXsnCV property.
     * 
     */
    public float getIntraPulseXsnCV() {
        return intraPulseXsnCV;
    }

    /**
     * Sets the value of the intraPulseXsnCV property.
     * 
     */
    public void setIntraPulseXsnCV(float value) {
        this.intraPulseXsnCV = value;
    }

    /**
     * Gets the value of the interPulseXsnCV property.
     * 
     */
    public float getInterPulseXsnCV() {
        return interPulseXsnCV;
    }

    /**
     * Sets the value of the interPulseXsnCV property.
     * 
     */
    public void setInterPulseXsnCV(float value) {
        this.interPulseXsnCV = value;
    }

    /**
     * Gets the value of the diffusionXsnCV property.
     * 
     */
    public float getDiffusionXsnCV() {
        return diffusionXsnCV;
    }

    /**
     * Sets the value of the diffusionXsnCV property.
     * 
     */
    public void setDiffusionXsnCV(float value) {
        this.diffusionXsnCV = value;
    }

    /**
     * Gets the value of the pulseWidthMeanSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPulseWidthMeanSeconds() {
        return pulseWidthMeanSeconds;
    }

    /**
     * Sets the value of the pulseWidthMeanSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPulseWidthMeanSeconds(Float value) {
        this.pulseWidthMeanSeconds = value;
    }

    /**
     * Gets the value of the ipdMeanSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getIpdMeanSeconds() {
        return ipdMeanSeconds;
    }

    /**
     * Sets the value of the ipdMeanSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setIpdMeanSeconds(Float value) {
        this.ipdMeanSeconds = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link SupportedNucleotides }
     *     
     */
    public SupportedNucleotides getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportedNucleotides }
     *     
     */
    public void setBase(SupportedNucleotides value) {
        this.base = value;
    }

    /**
     * Gets the value of the nucleotide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNucleotide() {
        return nucleotide;
    }

    /**
     * Sets the value of the nucleotide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNucleotide(String value) {
        this.nucleotide = value;
    }

    /**
     * Gets the value of the wavelength property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWavelength() {
        return wavelength;
    }

    /**
     * Sets the value of the wavelength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWavelength(Float value) {
        this.wavelength = value;
    }

    /**
     * Gets the value of the compoundID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompoundID() {
        return compoundID;
    }

    /**
     * Sets the value of the compoundID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompoundID(String value) {
        this.compoundID = value;
    }

    /**
     * Gets the value of the lotID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotID() {
        return lotID;
    }

    /**
     * Sets the value of the lotID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotID(String value) {
        this.lotID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Values">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}float" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="NumberFilterBins" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "values"
    })
    public static class Spectrum {

        @XmlElement(name = "Values", required = true)
        protected AnalogType.Spectrum.Values values;
        @XmlAttribute(name = "NumberFilterBins", required = true)
        protected int numberFilterBins;

        /**
         * Gets the value of the values property.
         * 
         * @return
         *     possible object is
         *     {@link AnalogType.Spectrum.Values }
         *     
         */
        public AnalogType.Spectrum.Values getValues() {
            return values;
        }

        /**
         * Sets the value of the values property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnalogType.Spectrum.Values }
         *     
         */
        public void setValues(AnalogType.Spectrum.Values value) {
            this.values = value;
        }

        /**
         * Gets the value of the numberFilterBins property.
         * 
         */
        public int getNumberFilterBins() {
            return numberFilterBins;
        }

        /**
         * Sets the value of the numberFilterBins property.
         * 
         */
        public void setNumberFilterBins(int value) {
            this.numberFilterBins = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}float" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Values {

            @XmlElement(name = "Value", type = Float.class)
            protected List<Float> value;

            /**
             * Gets the value of the value property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the value property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValue().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Float }
             * 
             * 
             */
            public List<Float> getValue() {
                if (value == null) {
                    value = new ArrayList<Float>();
                }
                return this.value;
            }

        }

    }

}
