//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.19 at 11:50:03 AM PST 
//


package com.pacificbiosciences.pacbiobasedatamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MapType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MapType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}KeyValueMap"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MapType", propOrder = {
    "keyValueMap"
})
public class MapType {

    @XmlElement(name = "KeyValueMap", required = true)
    protected KeyValueMap keyValueMap;

    /**
     * Gets the value of the keyValueMap property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValueMap }
     *     
     */
    public KeyValueMap getKeyValueMap() {
        return keyValueMap;
    }

    /**
     * Sets the value of the keyValueMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValueMap }
     *     
     */
    public void setKeyValueMap(KeyValueMap value) {
        this.keyValueMap = value;
    }

}
