//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 01:17:39 PM PDT 
//


package com.pacificbiosciences.pacbiobasedatamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MapType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MapType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}KeyValueMap"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MapType", propOrder = {
    "keyValueMap"
})
public class MapType {

    @XmlElement(name = "KeyValueMap", required = true)
    protected KeyValueMap keyValueMap;

    /**
     * Gets the value of the keyValueMap property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValueMap }
     *     
     */
    public KeyValueMap getKeyValueMap() {
        return keyValueMap;
    }

    /**
     * Sets the value of the keyValueMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValueMap }
     *     
     */
    public void setKeyValueMap(KeyValueMap value) {
        this.keyValueMap = value;
    }

}
