//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.18 at 03:16:30 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pacificbiosciences.com/PacBioBaseDataModel.xsd",
        xmlns = {@XmlNs(prefix = "pbbase", namespaceURI = "http://pacificbiosciences.com/PacBioBaseDataModel.xsd")},
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED
)
package com.pacificbiosciences.pacbiobasedatamodel;
import javax.xml.bind.annotation.XmlNs;
