//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.19 at 11:50:03 AM PST 
//


package com.pacificbiosciences.pacbiobasedatamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A more specific binding kit representation (includes SupplyKit fields). 
 * 
 * <p>Java class for SupplyKitBinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplyKitBinding"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}PartNumberType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Control" type="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}SupplyKitControl" minOccurs="0"/&gt;
 *         &lt;element name="IsControlUsed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplyKitBinding", propOrder = {
    "control",
    "isControlUsed"
})
public class SupplyKitBinding
    extends PartNumberType
{

    @XmlElement(name = "Control")
    protected SupplyKitControl control;
    @XmlElement(name = "IsControlUsed")
    protected Boolean isControlUsed;

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link SupplyKitControl }
     *     
     */
    public SupplyKitControl getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplyKitControl }
     *     
     */
    public void setControl(SupplyKitControl value) {
        this.control = value;
    }

    /**
     * Gets the value of the isControlUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsControlUsed() {
        return isControlUsed;
    }

    /**
     * Sets the value of the isControlUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsControlUsed(Boolean value) {
        this.isControlUsed = value;
    }

}
