//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.06 at 11:45:18 AM PDT 
//


package com.pacificbiosciences.pacbiosampleinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.pacificbiosciences.pacbiobasedatamodel.StrictEntityType;


/**
 * The actual biological sample; this could be prep'd, or in original form; could be bound, or annealed...
 * 
 * <p>Java class for BioSampleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BioSampleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}StrictEntityType">
 *       &lt;sequence>
 *         &lt;element ref="{http://pacificbiosciences.com/PacBioSampleInfo.xsd}BioSamples" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DateReceived" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Organism" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DNAType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Concentration" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="QuantificationMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SMRTBellConcentration" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="SMRTBellQuantificationMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BufferName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SamplePrepKit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TargetLibrarySize" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BioSampleType", propOrder = {
    "bioSamples"
})
@XmlSeeAlso({
    BarcodedSampleType.class
})
public class BioSampleType
    extends StrictEntityType
{

    @XmlElement(name = "BioSamples")
    protected BioSamples bioSamples;
    @XmlAttribute(name = "DateReceived")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateReceived;
    @XmlAttribute(name = "Organism")
    protected String organism;
    @XmlAttribute(name = "Reference")
    protected String reference;
    @XmlAttribute(name = "DNAType")
    protected String dnaType;
    @XmlAttribute(name = "Concentration")
    protected Float concentration;
    @XmlAttribute(name = "QuantificationMethod")
    protected String quantificationMethod;
    @XmlAttribute(name = "SMRTBellConcentration")
    protected Float smrtBellConcentration;
    @XmlAttribute(name = "SMRTBellQuantificationMethod")
    protected String smrtBellQuantificationMethod;
    @XmlAttribute(name = "BufferName")
    protected String bufferName;
    @XmlAttribute(name = "SamplePrepKit")
    protected String samplePrepKit;
    @XmlAttribute(name = "TargetLibrarySize")
    protected String targetLibrarySize;

    /**
     * Gets the value of the bioSamples property.
     * 
     * @return
     *     possible object is
     *     {@link BioSamples }
     *     
     */
    public BioSamples getBioSamples() {
        return bioSamples;
    }

    /**
     * Sets the value of the bioSamples property.
     * 
     * @param value
     *     allowed object is
     *     {@link BioSamples }
     *     
     */
    public void setBioSamples(BioSamples value) {
        this.bioSamples = value;
    }

    /**
     * Gets the value of the dateReceived property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateReceived() {
        return dateReceived;
    }

    /**
     * Sets the value of the dateReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateReceived(XMLGregorianCalendar value) {
        this.dateReceived = value;
    }

    /**
     * Gets the value of the organism property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganism() {
        return organism;
    }

    /**
     * Sets the value of the organism property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganism(String value) {
        this.organism = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the dnaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNAType() {
        return dnaType;
    }

    /**
     * Sets the value of the dnaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNAType(String value) {
        this.dnaType = value;
    }

    /**
     * Gets the value of the concentration property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getConcentration() {
        return concentration;
    }

    /**
     * Sets the value of the concentration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setConcentration(Float value) {
        this.concentration = value;
    }

    /**
     * Gets the value of the quantificationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantificationMethod() {
        return quantificationMethod;
    }

    /**
     * Sets the value of the quantificationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantificationMethod(String value) {
        this.quantificationMethod = value;
    }

    /**
     * Gets the value of the smrtBellConcentration property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSMRTBellConcentration() {
        return smrtBellConcentration;
    }

    /**
     * Sets the value of the smrtBellConcentration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSMRTBellConcentration(Float value) {
        this.smrtBellConcentration = value;
    }

    /**
     * Gets the value of the smrtBellQuantificationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMRTBellQuantificationMethod() {
        return smrtBellQuantificationMethod;
    }

    /**
     * Sets the value of the smrtBellQuantificationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMRTBellQuantificationMethod(String value) {
        this.smrtBellQuantificationMethod = value;
    }

    /**
     * Gets the value of the bufferName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBufferName() {
        return bufferName;
    }

    /**
     * Sets the value of the bufferName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBufferName(String value) {
        this.bufferName = value;
    }

    /**
     * Gets the value of the samplePrepKit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplePrepKit() {
        return samplePrepKit;
    }

    /**
     * Sets the value of the samplePrepKit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplePrepKit(String value) {
        this.samplePrepKit = value;
    }

    /**
     * Gets the value of the targetLibrarySize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetLibrarySize() {
        return targetLibrarySize;
    }

    /**
     * Sets the value of the targetLibrarySize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetLibrarySize(String value) {
        this.targetLibrarySize = value;
    }

}
