//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.06 at 11:45:18 AM PDT 
//


package com.pacificbiosciences.pacbiosampleinfo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pacificbiosciences.pacbiosampleinfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BioSample_QNAME = new QName("http://pacificbiosciences.com/PacBioSampleInfo.xsd", "BioSample");
    private final static QName _BarcodedSamplePointersBarcodedSamplePointer_QNAME = new QName("http://pacificbiosciences.com/PacBioSampleInfo.xsd", "BarcodedSamplePointer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pacificbiosciences.pacbiosampleinfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BarcodedSampleType }
     * 
     */
    public BarcodedSampleType createBarcodedSampleType() {
        return new BarcodedSampleType();
    }

    /**
     * Create an instance of {@link BioSamplePointers }
     * 
     */
    public BioSamplePointers createBioSamplePointers() {
        return new BioSamplePointers();
    }

    /**
     * Create an instance of {@link BarcodedSamplePointers }
     * 
     */
    public BarcodedSamplePointers createBarcodedSamplePointers() {
        return new BarcodedSamplePointers();
    }

    /**
     * Create an instance of {@link BioSampleType }
     * 
     */
    public BioSampleType createBioSampleType() {
        return new BioSampleType();
    }

    /**
     * Create an instance of {@link BioSamples }
     * 
     */
    public BioSamples createBioSamples() {
        return new BioSamples();
    }

    /**
     * Create an instance of {@link BarcodedSampleType.Barcodes }
     * 
     */
    public BarcodedSampleType.Barcodes createBarcodedSampleTypeBarcodes() {
        return new BarcodedSampleType.Barcodes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BioSampleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioSampleInfo.xsd", name = "BioSample")
    public JAXBElement<BioSampleType> createBioSample(BioSampleType value) {
        return new JAXBElement<BioSampleType>(_BioSample_QNAME, BioSampleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioSampleInfo.xsd", name = "BarcodedSamplePointer", scope = BarcodedSamplePointers.class)
    @XmlIDREF
    public JAXBElement<Object> createBarcodedSamplePointersBarcodedSamplePointer(Object value) {
        return new JAXBElement<Object>(_BarcodedSamplePointersBarcodedSamplePointer_QNAME, Object.class, BarcodedSamplePointers.class, value);
    }

}
