//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.06 at 11:45:18 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pacificbiosciences.com/PacBioSampleInfo.xsd",
 xmlns = {@XmlNs(prefix = "pbsample", namespaceURI = "http://pacificbiosciences.com/PacBioSampleInfo.xsd")},
 elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
 attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED
 )
package com.pacificbiosciences.pacbiosampleinfo;
import javax.xml.bind.annotation.XmlNs;
