//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 02:50:32 PM PST 
//


package com.pacificbiosciences.pacbiodatasets;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContigSetMetadataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContigSetMetadataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://pacificbiosciences.com/PacBioDatasets.xsd}DataSetMetadataType">
 *       &lt;sequence>
 *         &lt;element name="Organism" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ploidy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://pacificbiosciences.com/PacBioDatasets.xsd}Contigs"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContigSetMetadataType", propOrder = {
    "organism",
    "ploidy",
    "contigs"
})
public class ContigSetMetadataType
    extends DataSetMetadataType
{

    @XmlElement(name = "Organism")
    protected String organism;
    @XmlElement(name = "Ploidy")
    protected String ploidy;
    @XmlElement(name = "Contigs", required = true)
    protected Contigs contigs;

    /**
     * Gets the value of the organism property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganism() {
        return organism;
    }

    /**
     * Sets the value of the organism property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganism(String value) {
        this.organism = value;
    }

    /**
     * Gets the value of the ploidy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPloidy() {
        return ploidy;
    }

    /**
     * Sets the value of the ploidy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPloidy(String value) {
        this.ploidy = value;
    }

    /**
     * Gets the value of the contigs property.
     * 
     * @return
     *     possible object is
     *     {@link Contigs }
     *     
     */
    public Contigs getContigs() {
        return contigs;
    }

    /**
     * Sets the value of the contigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contigs }
     *     
     */
    public void setContigs(Contigs value) {
        this.contigs = value;
    }

}
