//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.06 at 11:45:18 AM PDT 
//


package com.pacificbiosciences.pacbiodatasets;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pacificbiosciences.pacbiodatasets package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataSet_QNAME = new QName("http://pacificbiosciences.com/PacBioDatasets.xsd", "DataSet");
    private final static QName _DataSetRoot_QNAME = new QName("http://pacificbiosciences.com/PacBioDatasets.xsd", "DataSetRoot");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pacificbiosciences.pacbiodatasets
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSetType }
     * 
     */
    public DataSetType createDataSetType() {
        return new DataSetType();
    }

    /**
     * Create an instance of {@link Contigs }
     * 
     */
    public Contigs createContigs() {
        return new Contigs();
    }

    /**
     * Create an instance of {@link DataSetMetadataType }
     * 
     */
    public DataSetMetadataType createDataSetMetadataType() {
        return new DataSetMetadataType();
    }

    /**
     * Create an instance of {@link SubsetType }
     * 
     */
    public SubsetType createSubsetType() {
        return new SubsetType();
    }

    /**
     * Create an instance of {@link ReadSetMetadataType }
     * 
     */
    public ReadSetMetadataType createReadSetMetadataType() {
        return new ReadSetMetadataType();
    }

    /**
     * Create an instance of {@link SubreadSet }
     * 
     */
    public SubreadSet createSubreadSet() {
        return new SubreadSet();
    }

    /**
     * Create an instance of {@link SubreadSetType }
     * 
     */
    public SubreadSetType createSubreadSetType() {
        return new SubreadSetType();
    }

    /**
     * Create an instance of {@link ReadSetType }
     * 
     */
    public ReadSetType createReadSetType() {
        return new ReadSetType();
    }

    /**
     * Create an instance of {@link DataSetType.Filters }
     * 
     */
    public DataSetType.Filters createDataSetTypeFilters() {
        return new DataSetType.Filters();
    }

    /**
     * Create an instance of {@link DataSetType.DataSets }
     * 
     */
    public DataSetType.DataSets createDataSetTypeDataSets() {
        return new DataSetType.DataSets();
    }

    /**
     * Create an instance of {@link ContigSet }
     * 
     */
    public ContigSet createContigSet() {
        return new ContigSet();
    }

    /**
     * Create an instance of {@link ContigSetType }
     * 
     */
    public ContigSetType createContigSetType() {
        return new ContigSetType();
    }

    /**
     * Create an instance of {@link ContigSetMetadataType }
     * 
     */
    public ContigSetMetadataType createContigSetMetadataType() {
        return new ContigSetMetadataType();
    }

    /**
     * Create an instance of {@link ReferenceSet }
     * 
     */
    public ReferenceSet createReferenceSet() {
        return new ReferenceSet();
    }

    /**
     * Create an instance of {@link BarcodeSet }
     * 
     */
    public BarcodeSet createBarcodeSet() {
        return new BarcodeSet();
    }

    /**
     * Create an instance of {@link BarcodeSetType }
     * 
     */
    public BarcodeSetType createBarcodeSetType() {
        return new BarcodeSetType();
    }

    /**
     * Create an instance of {@link BarcodeSetMetadataType }
     * 
     */
    public BarcodeSetMetadataType createBarcodeSetMetadataType() {
        return new BarcodeSetMetadataType();
    }

    /**
     * Create an instance of {@link ConsensusAlignmentSet }
     * 
     */
    public ConsensusAlignmentSet createConsensusAlignmentSet() {
        return new ConsensusAlignmentSet();
    }

    /**
     * Create an instance of {@link AlignmentSetType }
     * 
     */
    public AlignmentSetType createAlignmentSetType() {
        return new AlignmentSetType();
    }

    /**
     * Create an instance of {@link AlignmentSetMetadataType }
     * 
     */
    public AlignmentSetMetadataType createAlignmentSetMetadataType() {
        return new AlignmentSetMetadataType();
    }

    /**
     * Create an instance of {@link DataSetRootType }
     * 
     */
    public DataSetRootType createDataSetRootType() {
        return new DataSetRootType();
    }

    /**
     * Create an instance of {@link Subsets }
     * 
     */
    public Subsets createSubsets() {
        return new Subsets();
    }

    /**
     * Create an instance of {@link ConsensusReadSet }
     * 
     */
    public ConsensusReadSet createConsensusReadSet() {
        return new ConsensusReadSet();
    }

    /**
     * Create an instance of {@link HdfSubreadSet }
     * 
     */
    public HdfSubreadSet createHdfSubreadSet() {
        return new HdfSubreadSet();
    }

    /**
     * Create an instance of {@link AlignmentSet }
     * 
     */
    public AlignmentSet createAlignmentSet() {
        return new AlignmentSet();
    }

    /**
     * Create an instance of {@link Contigs.Contig }
     * 
     */
    public Contigs.Contig createContigsContig() {
        return new Contigs.Contig();
    }

    /**
     * Create an instance of {@link SubreadSetMetadataType }
     * 
     */
    public SubreadSetMetadataType createSubreadSetMetadataType() {
        return new SubreadSetMetadataType();
    }

    /**
     * Create an instance of {@link DataSetMetadataType.Provenance }
     * 
     */
    public DataSetMetadataType.Provenance createDataSetMetadataTypeProvenance() {
        return new DataSetMetadataType.Provenance();
    }

    /**
     * Create an instance of {@link SubsetType.Filters }
     * 
     */
    public SubsetType.Filters createSubsetTypeFilters() {
        return new SubsetType.Filters();
    }

    /**
     * Create an instance of {@link ReadSetMetadataType.SummaryStats }
     * 
     */
    public ReadSetMetadataType.SummaryStats createReadSetMetadataTypeSummaryStats() {
        return new ReadSetMetadataType.SummaryStats();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioDatasets.xsd", name = "DataSet")
    public JAXBElement<DataSetType> createDataSet(DataSetType value) {
        return new JAXBElement<DataSetType>(_DataSet_QNAME, DataSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSetRootType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pacificbiosciences.com/PacBioDatasets.xsd", name = "DataSetRoot")
    public JAXBElement<DataSetRootType> createDataSetRoot(DataSetRootType value) {
        return new JAXBElement<DataSetRootType>(_DataSetRoot_QNAME, DataSetRootType.class, null, value);
    }

}
