//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.19 at 11:50:03 AM PST 
//


package com.pacificbiosciences.pacbiodatasets;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.pacificbiosciences.pacbiobasedatamodel.DataPointers;
import com.pacificbiosciences.pacbiobasedatamodel.FilterType;
import com.pacificbiosciences.pacbiobasedatamodel.StrictEntityType;


/**
 * <p>Java class for SubsetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubsetType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}StrictEntityType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Filters" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Filter" type="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}FilterType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}DataPointers" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubsetType", propOrder = {
    "filters",
    "dataPointers"
})
public class SubsetType
    extends StrictEntityType
{

    @XmlElement(name = "Filters")
    protected SubsetType.Filters filters;
    @XmlElement(name = "DataPointers", namespace = "http://pacificbiosciences.com/PacBioBaseDataModel.xsd")
    protected DataPointers dataPointers;

    /**
     * Gets the value of the filters property.
     * 
     * @return
     *     possible object is
     *     {@link SubsetType.Filters }
     *     
     */
    public SubsetType.Filters getFilters() {
        return filters;
    }

    /**
     * Sets the value of the filters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubsetType.Filters }
     *     
     */
    public void setFilters(SubsetType.Filters value) {
        this.filters = value;
    }

    /**
     * Gets the value of the dataPointers property.
     * 
     * @return
     *     possible object is
     *     {@link DataPointers }
     *     
     */
    public DataPointers getDataPointers() {
        return dataPointers;
    }

    /**
     * Sets the value of the dataPointers property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPointers }
     *     
     */
    public void setDataPointers(DataPointers value) {
        this.dataPointers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Filter" type="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}FilterType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class Filters {

        @XmlElement(name = "Filter", required = true)
        protected List<FilterType> filter;

        /**
         * Gets the value of the filter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the filter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFilter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FilterType }
         * 
         * 
         */
        public List<FilterType> getFilter() {
            if (filter == null) {
                filter = new ArrayList<FilterType>();
            }
            return this.filter;
        }

    }

}
