//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.19 at 11:50:03 AM PST 
//


package com.pacificbiosciences.pacbiodatamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.pacificbiosciences.pacbiobasedatamodel.DataEntityType;


/**
 * <p>Java class for AssayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssayType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://pacificbiosciences.com/PacBioBaseDataModel.xsd}DataEntityType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://pacificbiosciences.com/PacBioDataModel.xsd}SubreadSets"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssayType", propOrder = {
    "subreadSets"
})
public class AssayType
    extends DataEntityType
{

    @XmlElement(name = "SubreadSets", required = true)
    protected SubreadSets subreadSets;

    /**
     * Gets the value of the subreadSets property.
     * 
     * @return
     *     possible object is
     *     {@link SubreadSets }
     *     
     */
    public SubreadSets getSubreadSets() {
        return subreadSets;
    }

    /**
     * Sets the value of the subreadSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubreadSets }
     *     
     */
    public void setSubreadSets(SubreadSets value) {
        this.subreadSets = value;
    }

}
