//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 04:52:36 PM PDT 
//


package com.pacificbiosciences.pacbiodatamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="IsValid" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Source" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="PlateId"/>
 *             &lt;enumeration value="PlateDefinition"/>
 *             &lt;enumeration value="SchemaVersion"/>
 *             &lt;enumeration value="DefType"/>
 *             &lt;enumeration value="Owner"/>
 *             &lt;enumeration value="CreatedBy"/>
 *             &lt;enumeration value="Comments"/>
 *             &lt;enumeration value="OutputPath"/>
 *             &lt;enumeration value="Collections"/>
 *             &lt;enumeration value="Collection"/>
 *             &lt;enumeration value="DNATemplatePrepKitDefinition"/>
 *             &lt;enumeration value="BindingKitDefinition"/>
 *             &lt;enumeration value="RunResources"/>
 *             &lt;enumeration value="CompatibleChipLayouts"/>
 *             &lt;enumeration value="ChipLayout"/>
 *             &lt;enumeration value="CompatibleSequencingKits"/>
 *             &lt;enumeration value="SequencingKit"/>
 *             &lt;enumeration value="RequiredTips"/>
 *             &lt;enumeration value="EstimatedTotalRunTime"/>
 *             &lt;enumeration value="RequiredSMRTCells"/>
 *             &lt;enumeration value="CollectionAutomation"/>
 *             &lt;enumeration value="Basecaller"/>
 *             &lt;enumeration value="SecondaryAnalysisAutomation"/>
 *             &lt;enumeration value="WellNo"/>
 *             &lt;enumeration value="SampleName"/>
 *             &lt;enumeration value="Barcode"/>
 *             &lt;enumeration value="AcquisitionTime"/>
 *             &lt;enumeration value="InsertSize"/>
 *             &lt;enumeration value="ReuseComplex"/>
 *             &lt;enumeration value="StageHS"/>
 *             &lt;enumeration value="NumberOfCollections"/>
 *             &lt;enumeration value="Confidence"/>
 *             &lt;enumeration value="SampleComment"/>
 *             &lt;enumeration value="StrobeByTime"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ElementPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SupplementalInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Validation")
public class Validation {

    @XmlAttribute(name = "IsValid", required = true)
    protected boolean isValid;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "Source", required = true)
    protected String source;
    @XmlAttribute(name = "ElementPath")
    protected String elementPath;
    @XmlAttribute(name = "SupplementalInfo")
    protected String supplementalInfo;

    /**
     * Gets the value of the isValid property.
     * 
     */
    public boolean isIsValid() {
        return isValid;
    }

    /**
     * Sets the value of the isValid property.
     * 
     */
    public void setIsValid(boolean value) {
        this.isValid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the elementPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementPath() {
        return elementPath;
    }

    /**
     * Sets the value of the elementPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementPath(String value) {
        this.elementPath = value;
    }

    /**
     * Gets the value of the supplementalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementalInfo() {
        return supplementalInfo;
    }

    /**
     * Sets the value of the supplementalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementalInfo(String value) {
        this.supplementalInfo = value;
    }

}
